/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.example.View;
import javax.swing.JOptionPane;
import org.example.Controller.ClienteController;
import org.example.Model.Cliente;
/**
 *
 * @author maycon
 */
public class CadrastrarCliente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadrastrarCliente.class.getName());
    private final ClienteController clienteController;
    private boolean modoEdicao = false;
    private String cpfOriginal;
   
    public CadrastrarCliente(java.awt.Frame parent, boolean modal,
            ClienteController clienteController, Cliente cliente) {
        super(parent, modal);
        initComponents();
        this.clienteController = clienteController;
        setLocationRelativeTo(null);
        setResizable(false);
        if(cliente != null) {
        modoEdicao = true;
        cpfOriginal = cliente.getCpf();

        txtNomeCds.setText(cliente.getNome());
        txtCpfCds.setText(cliente.getCpf());

        txtCpfCds.setEnabled(false);
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jlabel1 = new javax.swing.JLabel();
        JLabel2 = new javax.swing.JLabel();
        txtNomeCds = new javax.swing.JTextField();
        txtCpfCds = new javax.swing.JTextField();
        btnCancelarCdsCliente = new javax.swing.JButton();
        btnAvancarCdsCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadrastrar novo cliente");

        Jlabel1.setText("Nome:");

        JLabel2.setText("CPF:");

        btnCancelarCdsCliente.setText("Cancelar");
        btnCancelarCdsCliente.addActionListener(this::btnCancelarCdsClienteActionPerformed);

        btnAvancarCdsCliente.setText("Salvar");
        btnAvancarCdsCliente.addActionListener(this::btnAvancarCdsClienteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jlabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomeCds, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCpfCds, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnCancelarCdsCliente)
                        .addGap(36, 36, 36)
                        .addComponent(btnAvancarCdsCliente)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlabel1)
                    .addComponent(txtNomeCds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfCds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarCdsCliente)
                    .addComponent(btnAvancarCdsCliente))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvancarCdsClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarCdsClienteActionPerformed
   try {

        String nome = txtNomeCds.getText().trim();
        String cpf = txtCpfCds.getText().trim();
        if(modoEdicao){
            clienteController.atualizarCliente(nome, cpfOriginal);
        }else{
            clienteController.adicionarCliente(nome, cpf);
        }
        JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso!");

        dispose();

    } catch (IllegalArgumentException e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAvancarCdsClienteActionPerformed

    private void btnCancelarCdsClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCdsClienteActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarCdsClienteActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel2;
    private javax.swing.JLabel Jlabel1;
    private javax.swing.JButton btnAvancarCdsCliente;
    private javax.swing.JButton btnCancelarCdsCliente;
    private javax.swing.JTextField txtCpfCds;
    private javax.swing.JTextField txtNomeCds;
    // End of variables declaration//GEN-END:variables
}
