/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.example.View;
import javax.swing.JOptionPane;
import org.example.Controller.CarroController;
import org.example.Model.Carro;
import org.example.Controller.ClienteController;
import org.example.Model.Cliente;
/**
 *
 * @author maycon
 */
public class CadrastrarCarro extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadrastrarCarro.class.getName());
    private final CarroController carroController;
    private boolean modoEdicao = false;
    private String placaOriginal;
    private final ClienteController clienteController;
    /**
     * Creates new form CadrastrarCarro
     */
    public CadrastrarCarro(
        java.awt.Frame parent,
        boolean modal,
        CarroController carroController,
        ClienteController clienteController,
        Carro carro
    ) {

    super(parent, modal);

    initComponents();

    this.carroController = carroController;
    this.clienteController = clienteController;

    setLocationRelativeTo(null);
    setResizable(false);
    carregarClientes();
    if (carro != null) {

        modoEdicao = true;
        placaOriginal = carro.getPlaca();

        txtModeloCds.setText(carro.getModelo());
        txtMarcaCds.setText(carro.getMarca());
        txtPlacaCds.setText(carro.getPlaca());
        cmbProprietario.setSelectedItem(carro.getProprietario());

        txtPlacaCds.setEnabled(false);
    }
}
    
    private void carregarClientes() {

    cmbProprietario.removeAllItems();

    for (Cliente cliente : clienteController.listarClientes()) {
        cmbProprietario.addItem(cliente.getNome());
    }

}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtModeloCds = new javax.swing.JTextField();
        txtMarcaCds = new javax.swing.JTextField();
        txtPlacaCds = new javax.swing.JTextField();
        btnCancelarsdCds = new javax.swing.JButton();
        btnSalvarCds = new javax.swing.JButton();
        cmbProprietario = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Modelo:");

        jLabel2.setText("Marca:");

        jLabel3.setText("Placa:");

        jLabel4.setText("Proprietario:");

        txtModeloCds.addActionListener(this::txtModeloCdsActionPerformed);

        btnCancelarsdCds.setText("Cancelar");
        btnCancelarsdCds.addActionListener(this::btnCancelarsdCdsActionPerformed);

        btnSalvarCds.setText("Salvar");
        btnSalvarCds.addActionListener(this::btnSalvarCdsActionPerformed);

        cmbProprietario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProprietario.addActionListener(this::cmbProprietarioActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelarsdCds)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalvarCds))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(cmbProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPlacaCds)
                            .addComponent(txtModeloCds)
                            .addComponent(txtMarcaCds))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtModeloCds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMarcaCds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPlacaCds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarsdCds)
                    .addComponent(btnSalvarCds))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModeloCdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloCdsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloCdsActionPerformed

    private void btnSalvarCdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCdsActionPerformed
        // TODO add your handling code here:
try {
        String modelo = txtModeloCds.getText().trim();
        String marca = txtMarcaCds.getText().trim();
        String placa = txtPlacaCds.getText().trim();
        
        String regexPlaca = "^[A-Z]{3}-?[0-9][A-Z0-9][0-9]{2}$";
        
        if (placa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe a placa do veículo.", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtPlacaCds.requestFocus();
            return;
        }

        if (!placa.matches(regexPlaca)) {
            JOptionPane.showMessageDialog(this, "Placa inválida! Use o formato ABC-1234 ou ABC1D23.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            txtPlacaCds.requestFocus();
            return;
        }
        int indexSelecionado = cmbProprietario.getSelectedIndex();
        
        if (indexSelecionado == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um proprietário.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Cliente clienteSelecionado = clienteController.listarClientes().get(indexSelecionado);
        String cpf = clienteSelecionado.getCpf();

        if (modoEdicao) {
            carroController.atualizarCarro(
                modelo,
                marca,
                placaOriginal
            );
        } else {
            // 3. Agora a variável 'cpf' existe e é enviada corretamente!
            carroController.adicionarCarro(
                modelo,
                marca,
                placa,
                cpf
            );
        }

        JOptionPane.showMessageDialog(this, "Carro salvo com sucesso!");
        dispose();

    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(
            this,
            e.getMessage(),
            "Erro",
            JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnSalvarCdsActionPerformed

    private void btnCancelarsdCdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarsdCdsActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarsdCdsActionPerformed

    private void cmbProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProprietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProprietarioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarsdCds;
    private javax.swing.JButton btnSalvarCds;
    private javax.swing.JComboBox<String> cmbProprietario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtMarcaCds;
    private javax.swing.JTextField txtModeloCds;
    private javax.swing.JTextField txtPlacaCds;
    // End of variables declaration//GEN-END:variables
}
