/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.View;
import org.example.Controller.MecanicoController;
import org.example.repository.MecanicoRepository;
import javax.swing.table.DefaultTableModel;
import org.example.Model.Mecanico;
import java.util.List;
/**
 *
 * @author janana
 */
public class TelaMecanico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMecanico.class.getName());
    private MecanicoController mecanicoController;
    /**
     * Creates new form TelaMecanico
     */
    public TelaMecanico() {
        initComponents();
        MecanicoRepository repo = new MecanicoRepository();
        this.mecanicoController = new MecanicoController(repo);
        atualizarTabela();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botaoCadastrar = new javax.swing.JButton();
        botaoRemover = new javax.swing.JButton();
        botaoAtualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabMecanicos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciador de Mecânicos");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(this::botaoCadastrarActionPerformed);

        botaoRemover.setText("Remover");
        botaoRemover.addActionListener(this::botaoRemoverActionPerformed);

        botaoAtualizar.setText("Atualizar");
        botaoAtualizar.setToolTipText("");
        botaoAtualizar.addActionListener(this::botaoAtualizarActionPerformed);

        TabMecanicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Sálario", "Especialidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabMecanicos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TabMecanicosFocusGained(evt);
            }
        });
        TabMecanicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabMecanicosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabMecanicos);
        if (TabMecanicos.getColumnModel().getColumnCount() > 0) {
            TabMecanicos.getColumnModel().getColumn(0).setResizable(false);
            TabMecanicos.getColumnModel().getColumn(1).setResizable(false);
            TabMecanicos.getColumnModel().getColumn(2).setResizable(false);
            TabMecanicos.getColumnModel().getColumn(3).setResizable(false);
        }

        jButton1.setText("Voltar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabMecanicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabMecanicosMouseClicked
        botaoRemover.setEnabled(true);
        botaoAtualizar.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_TabMecanicosMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        FormularioMecanico formMec = new FormularioMecanico(mecanicoController);
    
    formMec.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            atualizarTabela();
        }
    });
    
    formMec.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void TabMecanicosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TabMecanicosFocusGained
         atualizarTabela();
    }//GEN-LAST:event_TabMecanicosFocusGained

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        int linhaSelecionada = TabMecanicos.getSelectedRow();

    if (linhaSelecionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um mecânico na tabela para remover.", "Mensagem", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    String nome = TabMecanicos.getValueAt(linhaSelecionada, 0).toString();
    String cpf = TabMecanicos.getValueAt(linhaSelecionada, 1).toString();

    int confirmacao = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        "Tem certeza que deseja remover o mecânico " + nome + " (CPF: " + cpf + ")?", 
        "Confirmar Remoção", 
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.QUESTION_MESSAGE
    );

    if (confirmacao == javax.swing.JOptionPane.YES_OPTION) {
        try {
            mecanicoController.removerMecanico(nome, cpf, TOP_ALIGNMENT, cpf);
            javax.swing.JOptionPane.showMessageDialog(this, "Mecânico removido com sucesso!");
            atualizarTabela();
            botaoRemover.setEnabled(false);
            botaoAtualizar.setEnabled(false);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_botaoRemoverActionPerformed
   }
    }
    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
          int linhaSelecionada = TabMecanicos.getSelectedRow();

    if (linhaSelecionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um mecânico.", "Mensagem", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    String cpfSelecionado = TabMecanicos.getValueAt(linhaSelecionada, 1).toString();

    FormularioMecanicoAtt formAtt = new FormularioMecanicoAtt(mecanicoController, cpfSelecionado);
    
    formAtt.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            atualizarTabela();
        }
    });
    
    formAtt.setVisible(true);
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         OficinaProject telaMec = new OficinaProject(); 
         telaMec.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void atualizarTabela() {
    
    DefaultTableModel model = (DefaultTableModel) TabMecanicos.getModel();
    model.setRowCount(0);
    List<Mecanico> lista = mecanicoController.listarMecanicos();

    for (Mecanico m : lista) {
        Object[] linha = {
            m.getNome(),
            m.getCpf(),
            m.getSalario(),
            m.getEspecialidade()
        };
        model.addRow(linha); 
    }
}
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabMecanicos;
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
